// "use client";
// import { useEffect, useState } from "react";
import Link from "next/link";
import "./globals.css";

// only use sever component
export const metadata = {
  title: "Web tutorials",
  description: "Generated by yennie",
};

export default async function RootLayout({ children }) {
  // client component
  // const [topics, setTopics] = useState();
  // useEffect(() => {
  //   fetch("http://localhost:9999/topics")
  //     .then((resp) => {
  //       return resp.json();
  //     })
  //     .then((result) => {
  //       setTopics(result);
  //     });
  // }, []);

  // sever component async
  const resp = await fetch("http://localhost:9999/topics", {
    cache: "no-store",
  });
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
